spring:
   profiles: 
      active: local
server:
   port: 8082
---
spring:
   profiles: local   
spring.jpa:
    hibernate:
      ddl-auto: create-drop
logging:
   level.org.springframework: WARN
---
spring:
   profiles: docker
spring.jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgresqlDialect
      ddl-auto: update
spring.datasource:
   driverClassName: org.postgresql.Driver 
   url: jdbc:postgresql://${POSTGRESQL_PORT_5432_TCP_ADDR}:${POSTGRESQL_PORT_5432_TCP_PORT}/postgres
   username: postgres
   password: secret
logging:
   level.org.springframework: INFO
server:
   port: 8082
   sessionTimeout: 30
   # Tomcat specifics
   tomcat:
      accessLogEnabled: false
      backgroundProcessorDelay: 30 # secs
