spring:
   profiles: 
      active: local
server:
   port: 8081
---
spring:
   profiles: local   
spring.jpa:
    hibernate:
      ddl-auto: create-drop
logging:
   level.org.springframework: WARN
---
spring:
   profiles: docker
spring.jpa:
    hibernate:
      ddl-auto: update
spring.datasource:
   driverClassName: org.postgresql.Driver 
   url: jdbc:postgresql://localhost:5432/usecase
   username: postgres
   password: secret
